### ISSUE TITLE
PR previews should use the MOLGENIS dev environment

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis-ops-helm#197]
### Which chart are you referring?
Jenkins

### How to reproduce
- Request a preview from Hubot
- Sign in as superuser
- Navigate to ```/api/permissions/invalid```

### Expected behavior
- Response contains a stackTrace

### Observed behavior
- Response doesn't contain a stackTrace because MOLGENIS runs in a production environment

**Comment by sidohaakma** [comment]
Fixed by #203
