### ISSUE TITLE
Jenkinsfile need to be upgraded because of a deprecation warning

### ISSUE THREAD

**Issue by christianhilbrands** [molgenis/molgenis-ops-helm#394]
### Which chart are you referring?
All repo's with a jenkins pipeline enabled

### How to reproduce
Make a PR or trigger a build with jenkins

### Expected behavior
Blue occean display progress of the build process.

### Observed behavior
Blue occean give's deprecation warning. 
[WARNING] label option is deprecated. To use a static pod template, use the ‘inheritFrom’ option.

**Comment by sidohaakma** [comment]
Closed by #411
